kind: pipeline
type: docker
name: run-tests

steps:
- name: launch-worker
  image: ubuntu:22.04
  environment:
    DEBIAN_FRONTEND: noninteractive
    DEBCONF_NONINTERACTIVE_SEEN: true
  commands:
  - apt-get update -y
  - apt-get install -y curl unzip python3 python3-pip python3-yaml
  - curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
  - unzip awscliv2.zip
  - ./aws/install
  - ./script.py $DRONE_REPO $DRONE_COMMIT_BRANCH $DRONE_COMMIT_SHA
  - aws --region ap-southeast-2 ec2 run-instances --cli-input-yaml file://cli-input.yaml
  # - head -n -0 /mnt/logs/*
