kind: pipeline
type: docker
name: run-tests

steps:
- name: launch-worker
  image: ubuntu:22.04
  commands:
  - apt-get update -y
  - apt-get install -y awscli
  - aws ec2 --region ap-southeast-2 run-instances --cli-input-yaml file://input.json
  # - head -n -0 /mnt/logs/*
