kind: pipeline
type: docker
name: run-tests

steps:
- name: launch-worker
  image: ubuntu:22.04
  environment:
    DEBIAN_FRONTEND: noninteractive
    DEBCONF_NONINTERACTIVE_SEEN: true
  commands:
  - apt-get update -y
  - apt-get install -y curl unzip
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - ./aws/install
  - aws ec2 --region ap-southeast-2 run-instances --cli-input-yaml file://cli-input.yaml
  # - head -n -0 /mnt/logs/*
